/*Nov 14*/
CREATE TABLE FOOD_VENDOR
(VendorID INTEGER PRIMARY KEY,
VendorName VARCHAR2(40) NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50),
City VARCHAR2(40) NOT NULL,
State VARCHAR2(2) NOT NULL,
Zip VARCHAR2(9) NOT NULL,
PhoneNumber INTEGER NOT NULL,
Email VARCHAR2(40) NOT NULL,
LOGO VARCHAR(200) NOT NULL);


/*Nov 20*/

/* Add CHECK Constraint for State Column */
ALTER TABLE FOOD_VENDOR
  ADD CONSTRAINT CK_STATE CHECK (State IN ('AL','AK','AZ','AR','CA','CO','CT',
    'DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI',
    'MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR',
    'PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'));
    
/* Change data format for FOOD_VENDOR */
ALTER TABLE FOODVENDOR
  MODIFY Zip VARCHAR2(5);    
  
/*Nov 27*/
/* Adding Foreign Key to MENU */
ALTER TABLE MENU
  ADD CONSTRAINT FK_VENDOR FOREIGN KEY (VENDORID) REFERENCES FOODVENDOR(VENDORID);
  
/* Adding Foreign Key to MENUITEM */
ALTER TABLE MENUITEM
  ADD CONSTRAINT FK_VENDOR_MENUITEM FOREIGN KEY (VENDORID) REFERENCES FOODVENDOR(VENDORID);
  
/* Changing table name (INGREDIENTS) */
ALTER TABLE INGREDIENTS
  RENAME TO INGREDIENT;
  
/* Changing table name (ITEMINGREDIENTS) */
ALTER TABLE ITEMINGREDIENTS 
  RENAME TO ITEMINGREDIENT;
  
/* Dropping VENDORID from INGREDIENT and change PK */
ALTER TABLE INGREDIENT
  DROP COLUMN VENDORID CASCADE CONSTRAINTS;

ALTER TABLE INGREDIENT
  ADD CONSTRAINT PK_INGREDIENT PRIMARY KEY (INGREDIENTID);
  
/* Change column name ITEMLOG */
ALTER TABLE ITEMLOG
  RENAME COLUMN CREATIONDATE TO DATECREATED;
  
/* Add Foreign Keys to ITEMLOG */
ALTER TABLE ITEMLOG
  ADD CONSTRAINT FK_MENUID_LOG FOREIGN KEY (MENUID) REFERENCES MENU(MENUID);
ALTER TABLE ITEMLOG  
  ADD CONSTRAINT FK_ITEMID_LOG FOREIGN KEY (ITEMID) REFERENCES MENUITEM(ITEMID);
ALTER TABLE ITEMLOG  
  ADD CONSTRAINT FK_VENDORID_LOG FOREIGN KEY (VENDORID) REFERENCES FOODVENDOR(VENDORID);
  
/* Drop VENDORID from LOCATION */
ALTER TABLE LOCATION
  DROP COLUMN VENDORID;
  
/* Change Colum Name LOCATION */
ALTER TABLE LOCATION
  RENAME COLUMN STATES TO STATE;
  
/*Add CHECK constraint for LOCATION STATE */
ALTER TABLE LOCATION
  ADD CONSTRAINT CK_STATE_LOCATION CHECK (STATE IN ('AL','AK','AZ','AR','CA','CO','CT',
    'DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI',
    'MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR',
    'PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'));

/* Add table CUSTOMER */
CREATE TABLE CUSTOMER
(CUSTOMERID NUMBER(10) NOT NULL PRIMARY KEY,
CUSTNAME VARCHAR2(30) NOT NULL,
CUSTADDRESS1 VARCHAR2(50) NOT NULL,
CUSTADDRESS2 VARCHAR2(50),
CUSTCITY VARCHAR2(20),
CUSTSTATE VARCHAR2(2),
CUSTZIP NUMBER(5),
CUSTPHONE NUMBER(10),
CUSTEMAIL VARCHAR(40));

ALTER TABLE CUSTOMER
  ADD CONSTRAINT CK_STATE_CUSTOMER CHECK (CUSTSTATE IN ('AL','AK','AZ','AR','CA','CO','CT',
    'DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI',
    'MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR',
    'PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'));
    

/* Nov 28 */
/* Creating ORDERHEADER table */
CREATE TABLE ORDERHEADER
(ORDERID NUMBER(7) NOT NULL,
CUSTOMERID NOT NULL,
ORDERDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ORDERTOTAL NUMBER(7,2) NOT NULL,
CONSTRAINT PK_ORDERID PRIMARY KEY (ORDERID),
CONSTRAINT FK_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID));

/* Creating ORDERDETAIL */
CREATE TABLE ORDERDETAIL
(ORDERID NOT NULL,
ITEMID NOT NULL,
QUANTITY NUMBER(3) NOT NULL,
CONSTRAINT FK_ORDERID_ORDERDETAIL FOREIGN KEY (ORDERID) REFERENCES ORDERHEADER(ORDERID),
CONSTRAINT FK_ITEMID_ORDERDETAIL FOREIGN KEY (ITEMID) REFERENCES MENUITEM(ITEMID),
CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDERID, ITEMID)); 

/* drop VENDORID in ITEMINGREDIENT and change PK */
ALTER TABLE ITEMINGREDIENT
  DROP COLUMN VENDORID CASCADE CONSTRAINTS; 

ALTER TABLE ITEMINGREDIENT
  ADD CONSTRAINT PK_ITEMINGREDIENT PRIMARY KEY (ITEMID, INGREDIENTID);
  

/* Change constraint of ITEMLOG */
ALTER TABLE ITEMLOG
  DROP CONSTRAINT ITEMLOGPK; 
  
ALTER TABLE ITEMLOG 
  ADD CONSTRAINT PK_ITEMLOG PRIMARY KEY (MENUID, ITEMID);
  
  
/* Nov 29*/
  
/* Add Customer Seq */
CREATE SEQUENCE CUSTOMER_SEQ
  MINVALUE 6000000
  MAXVALUE 9999999
  START WITH 6000000
  INCREMENT BY 20
  CACHE 20;
    
/* Add Ingredient Seq */
CREATE SEQUENCE INGREDIENT_SEQ
  MINVALUE 6000000
  MAXVALUE 99999999
  START WITH 6000000
  INCREMENT BY 1
  CACHE 20;
  
/* Add Menu Seq */
CREATE SEQUENCE MENU_SEQ
  MINVALUE 3000000
  MAXVALUE 99999999
  START WITH 3000000
  INCREMENT BY 1
  CACHE 20;

/* Add Foodvendor seq */
CREATE SEQUENCE FOODVENDOR_SEQ
  MINVALUE 1000000
  MAXVALUE 99999999
  START WITH 1000000
  INCREMENT BY 1
  CACHE 20;
  
/* Add Orderheader Seq */
CREATE SEQUENCE ORDERHEADER_SEQ
  MINVALUE 5000000
  MAXVALUE 99999999
  START WITH 5000000
  INCREMENT BY 1
  CACHE 20;

RENAME ORDERHEADER_SEQ TO ORDER_SEQ;

/* Add Schedule Seq */
CREATE SEQUENCE SCHEDULE_SEQ
  MINVALUE 4000000
  MAXVALUE 99999999
  START WITH 4000000
  INCREMENT BY 1
  CACHE 20;

/* Add LOCATION_SEQ */
CREATE SEQUENCE LOCATIONID_SEQ
  MINVALUE 7000000
  MAXVALUE 99999999
  START WITH 7000000
  INCREMENT BY 1
  CACHE 20;
  
/* Add dummy data to FOODVENDOR */
INSERT INTO FOODVENDOR
  VALUES (FOODVENDOR_SEQ.NEXTVAL, 'Jamaican Patty Wagon', '5324 Imagy Lane', NULL,'Atlanta', 'GA', 30305, 6785551234, 'jpw@fakemail.com', 'logo1000000'); 

INSERT INTO FOODVENDOR VALUES (FOODVENDOR_SEQ.NEXTVAL, 'Food VehiKale', '3095 Made Up Street', NULL, 'Atlanta', 'GA', 30319, 6784677841, 'foodvehikale@unrealmail.com', 'logo1000001');
INSERT INTO FOODVENDOR VALUES(FOODVENDOR_SEQ.NEXTVAL, 'Nacho Mamas Taco Truck', '5555 Happy St NE', 'Suite 12', 'Atlanta', 'GA', 30302, 6785551208, 'nacho@fakemail.com', 'logo1000002');

/*Add dummy data to LOCATION*/
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Atlantic Station', '201 17th St.', NULL, 'Atlanta', 'GA', 30328, 33.791544, -84.394664);
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Coca Cola Headquarters', '1 Coca-Cola Plaza', NULL, 'Atlanta', 'GA', 30313, 33.753965, -84.381388);
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Lenox Mall', '3393 Peachtree Rd NE', NULL, 'Atlanta', 'GA', 30326, 33.846672, -84.361943);
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Cumberland Mall', '1000 Cumberland Mall', NULL, 'Atlanta', 'GA', 30339, 33.880233,	-84.468629);
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Asbury Automotive Headquarters', '2905 Premiere Pkwy', NULL, 'Duluth', 'GA', 30097, 34.005757,	-84.093159);
INSERT INTO LOCATION VALUES (LOCATION_SEQ.NEXTVAL, 'Snellville City Hall', '2342 Oak Road', NULL, 'Snellville', 'GA', 30078, 33.85817, -84.015753);

/* Foreign keys for SCHEDULE */
ALTER TABLE SCHEDULE
  ADD CONSTRAINT LOCATION_FK FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(LOCATIONID);
  
ALTER TABLE SCHEDULE
  ADD CONSTRAINT VENDOR_FK FOREIGN KEY (VENDORID) REFERENCES FOODVENDOR(VENDORID);
 
ALTER TABLE SCHEDULE
  ADD CONSTRAINT MENU_FK FOREIGN KEY (MENUID) REFERENCES MENU(MENUID);
  
/* Add dummy data into MENU */
INSERT INTO MENU VALUES (MENU_SEQ.NEXTVAL, 'Standard','A flavorful taste of the Caribbean', (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000004),'menupic3000000');
INSERT INTO MENU VALUES (MENU_SEQ.NEXTVAL, 'Standard','Delicious healthy food with plenty of green power!', (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005),'menupic3000001');
INSERT INTO MENU VALUES (MENU_SEQ.NEXTVAL, 'Standard','Nachos, Tacos and more', (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000006),'menupic3000002');
INSERT INTO MENU VALUES (MENU_SEQ.NEXTVAL, 'New Year Specials','Special menu for New Year', (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005),'menupic3000003');

/* Add MENUITEM sequence */
CREATE SEQUENCE MENUITEM_SEQ
  MINVALUE 8000000
  MAXVALUE 99999999
  START WITH 8000000
  INCREMENT BY 1
  CACHE 20;
  
/* Nov 30*/
/* Add dummy data to MENUITEM */
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000004), 'Taco salad', 4.49, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000004), 'Curry Goat with Rice', 8.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005), 'Caesar Salad', 3.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000006), 'Spicy chicken quesadilla', 7.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005), 'Kale Smoothies', 5.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000006), 'Super nacho', 4.50, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005), 'Jerk chicken with Plantains', 15.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000004), 'Jolloff Rice and Boiled Eggs', 10.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000004), 'Oxtail with rice (small)', 12.00, NULL);
INSERT INTO MENUITEM VALUES (MENUITEM_SEQ.NEXTVAL, (SELECT VENDORID FROM FOODVENDOR WHERE VENDORID=1000005), 'Veggie Quesadilla', 9.00, NULL);

/* Add dummy data into ITEMLOG */
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000001), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000002), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000001), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000009), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000001), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000003), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000001), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000010), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000005), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000008), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000005), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000011), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000005), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000004), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000005), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000006), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000006), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000005), SYSDATE);
INSERT INTO ITEMLOG VALUES ((SELECT MENUID FROM MENU WHERE MENUID=3000006), (SELECT ITEMID FROM MENUITEM WHERE ITEMID=8000007), SYSDATE);

/* Add dummy data to INGREDIENT */
INSERT INTO INGREDIENT VALUES (INGREDIENT_SEQ.NEXTVAL, 'Cheese', 'Mexican Cheese', 'Ounces', '5', 0, 1, 0, 1, 0);
INSERT INTO INGREDIENT VALUES (INGREDIENT_SEQ.NEXTVAL, 'Tortilla', 'Corn Tortilla', 'Ounces', 25, 0, 0, 1, 0, 0);
INSERT INTO INGREDIENT VALUES (INGREDIENT_SEQ.NEXTVAL, 'Lettuce', 'Organic Lettuce', 'Ounces', 30, 0, 0, 0, 0, 0);
INSERT INTO INGREDIENT VALUES (INGREDIENT_SEQ.NEXTVAL, 'Rice', 'Long Grain', 'Ounces', 25, 0, 1, 0, 1, 0);

